package com.erp.system.erpsystem.model.enums;

public enum ActionType {
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    VIEW_USER,
    MARK_ATTENDANCE,
    VIEW_ATTENDANCE,
    EDIT_ATTENDANCE,
    CREATE_LEAVE,
    APPROVE_LEAVE,
    REJECT_LEAVE,
    VIEW_LEAVE,
    CREATE_PERMISSION_REQUEST,
    APPROVE_PERMISSION_REQUEST,
    REJECT_PERMISSION_REQUEST,
    VIEW_REPORTS
}
